export const LANDING_BACKGROUND = require('./restack-background.png')
export const SLOGAN = require('./slogan.png')
export const LOGO_LANDING = require('./logo.png')
export const FB = require('./fb.png')
export const GOOGLE = require('./google.png')
export const APPLE = require('./apple.png') 